import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { Providers } from "./providers"
import './globals.css'
import NavbarComponent from '@/components/navbar'
import FooterComponent from '@/components/footer'

const PlusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${PlusJakartaSans.className}`}>
        <Providers>
          <NavbarComponent />

          <main>
            {children}
          </main>

          <FooterComponent />
        </Providers>
      </body>
    </html>
  )
}
